### ISSUE TITLE
Cant make nvenc work for handbrake docker

### ISSUE THREAD

**Issue by MacGyver27** [zocker-160/handbrake-nvenc-docker#1]
Hey,

If I may ask for your help here..

I have successfully configured **nvidia-docker** for my graphic card to be used in docker containers - so my Plex is doing HW transcoding in docker. However I am struggling to get handbrake doing encoding via GPU.
![image](https://user-images.githubusercontent.com/6546231/73496125-34606f00-43b8-11ea-82e2-778b7eb0f9c7.png)

My GPU is Nvidia Quadro P2200. Per https://developer.nvidia.com/video-encode-decode-gpu-support-matrix it has **nvenc** chip..

So my setup is:
Debian 10
Nvidia Quadro P2200
Installed packages:
- nvidia-detect
- nvidia-driver
- nvidia-cuda-toolkit
- nvidia-container-runtime
- nvidia-container-toolkit

docker-compose.yml:
```yml
version: "3.7"

  handbrake:
    container_name: plex.529.handbrake.90.91
    image: jlesage/handbrake
    restart: always
    ports:
      - 52990:5800
      - 52991:5900
    expose:
      - 5800
      - 5900
    volumes:
      - /lvm/raid/private/media:/plex/media
      - /lvm/raid/private/data:/plex/data
      - $PWD/handbrake/config:/config:rw
      - $PWD/handbrake/storage:/storage:ro
    environment:
      - TZ=Europe/Prague
      - USER_ID=1000
      - GROUP_ID=994
      - NVIDIA_VISIBLE_DEVICES=GPU-d705d61e-a848-a592-e014-d196cd66eec9
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=900
```

/etc/docker/daemon.json:
```js
{
  "default-runtime": "nvidia",
  "runtimes": {
     "nvidia": {
       "path": "/usr/bin/nvidia-container-runtime",
       "runtimeArgs": []
       }
     }
}
```
Thanks, Michal

EDIT:
I installed Handbrake directly on host to see if can choose **nvenc** profile, but same result - it is not listed there :/

**Comment by zocker-160** [comment]
@MacGyver27 first of all I am really _really_ sorry for this super late reply, I didn't get any notification that an issue got opened :-((

first of all: the native Handbrake version that comes with the debian repo does not have NVENC support enabled at least I couldn't get it to work either.
That's why the docker container is recommended

your docker compose setup above doesn't have NVENC enabled either, because you are using the wrong image: `image: jlesage/handbrake` doesn't have NVENC support, which is the reason why I created my repo over here

have you tried it with my docker image? 
It should work using my instructions

**Comment by zocker-160** [comment]
it should look like this
![Screenshot_20200214_014936](https://user-images.githubusercontent.com/36563538/74491566-4b30b680-4ecc-11ea-8eeb-cfbd308a050b.png)

**Comment by MacGyver27** [comment]
Sorry my bad, I pasted old docker-compose.yml file there. I was building from your github repo:

```yml
version: "3.7"

services:
  handbrake:
    container_name: handbrake.539
    build: ./handbrake-nvenc-docker
    restart: always
    ports:
      - 53980:5800
      - 53981:5900
    expose:
      - 5800
      - 5900
    volumes:
      - $PWD/config:/config:rw
      - $PWD/storage:/storage:ro
    environment:
      - TZ=Europe/Prague
      - USER_ID=1000
      - GROUP_ID=994
      - NVIDIA_VISIBLE_DEVICES=GPU-d705d61e-a848-a592-e014-d196cd66eec9
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=900
```

Using Cuda from the repo for Debian 10 - which is 9.2:
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148
```

And still cant see it 🤔 :
![image](https://user-images.githubusercontent.com/6546231/74525533-9628e900-4f21-11ea-9985-2b875eb8a72a.png)

Thank you for your patience, Michal

**Comment by zocker-160** [comment]
do you have `nvidia-docker2` installed?

does this command work for you?
`docker run --rm --runtime nvidia nvidia/cuda:9.0-base nvidia-smi`

I sadly coudln't replicate your problem, it works for me using those files:
`docker-compose`:

```
version: "3.3"

services:
  handbrake:
    container_name: handbrake.539
    image: zocker160/handbrake-nvenc:latest
    restart: always
    ports:
      - 53980:5800
      - 53981:5900
    expose:
      - 5800
      - 5900
    volumes:
      - $PWD/test:/config:rw
      - $PWD/test:/storage:ro
    environment:
      - TZ=Europe/Berlin
      - USER_ID=1000
      - GROUP_ID=994
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=900
```
and `/etc/docker/daemon.json`:
```

{
    "default-runtime": "nvidia",
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}
```
